//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_line_apply_change_info
    {
        public long aid { get; set; }
        public long account_aid { get; set; }
        public string user_name { get; set; }
        public string email { get; set; }
        public string tel { get; set; }
        public string reason { get; set; }
        public Nullable<byte> if_permit { get; set; }
        public Nullable<byte> disable { get; set; }
        public string apply_datetime { get; set; }
        public string permit_datetime { get; set; }
    }
}
