//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_line_prm_roles
    {
        public long aid { get; set; }
        public long account_aid { get; set; }
        public int prm_organization_privilege_aid { get; set; }
        public Nullable<byte> disable { get; set; }
        public Nullable<byte> if_read { get; set; }
        public Nullable<byte> if_add { get; set; }
        public Nullable<byte> if_update { get; set; }
        public Nullable<byte> if_delete { get; set; }
        public Nullable<byte> if_default { get; set; }
    }
}
