//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_event_info
    {
        public long aid { get; set; }
        public string event_name { get; set; }
        public string event_name_en { get; set; }
        public Nullable<int> event_type { get; set; }
        public string event_apply_start_date { get; set; }
        public string event_apply_end_date { get; set; }
        public string event_act_start_date { get; set; }
        public string event_act_end_date { get; set; }
        public string event_act_start_date_time { get; set; }
        public string event_act_end_date_time { get; set; }
        public string event_intro { get; set; }
        public Nullable<int> location_info_aid { get; set; }
        public string location_address { get; set; }
        public string location_desc { get; set; }
        public Nullable<int> apply_limit_num { get; set; }
        public string event_link_url { get; set; }
        public string event_video_url { get; set; }
        public string event_information { get; set; }
        public Nullable<long> event_apply_form_aid { get; set; }
        public string event_apply_form { get; set; }
        public Nullable<long> event_pm { get; set; }
        public Nullable<long> event_admin { get; set; }
        public Nullable<long> acts29_church_aid { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
        public Nullable<byte> if_tra { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<byte> disable { get; set; }
    }
}
