//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class act_event_line_ticket
    {
        public long aid { get; set; }
        public Nullable<long> act_event_info_aid { get; set; }
        public string ticket_name { get; set; }
        public string ticket_desc { get; set; }
        public string ticket_apply_start_date { get; set; }
        public string ticket_apply_start_date_time { get; set; }
        public string ticket_apply_end_date { get; set; }
        public string ticket_apply_end_date_time { get; set; }
        public string ticket_valid_start_date { get; set; }
        public string ticket_valid_start_date_time { get; set; }
        public string ticket_valid_end_date { get; set; }
        public string ticket_valid_end_date_time { get; set; }
        public Nullable<int> ticket_pay_valid_hr { get; set; }
        public string ticket_pay_valid_date_time { get; set; }
        public Nullable<int> ticket_price { get; set; }
        public Nullable<int> ticket_quantity { get; set; }
        public Nullable<int> ticket_purchase_min_num { get; set; }
        public Nullable<int> ticket_purchase_max_num { get; set; }
        public Nullable<byte> if_apply { get; set; }
        public Nullable<byte> if_teampon { get; set; }
        public string apply_list { get; set; }
        public Nullable<byte> disable { get; set; }
    }
}
