//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acts29_church_line_donation_account_info
    {
        public int aid { get; set; }
        public Nullable<long> acts29_church_aid { get; set; }
        public string donate_bank_id { get; set; }
        public string donate_bank_name { get; set; }
        public string donate_bank_branches { get; set; }
        public Nullable<long> donate_account_id { get; set; }
        public string donate_account_name { get; set; }
        public Nullable<int> donate_account_virtual_id { get; set; }
        public Nullable<byte> if_tra_active { get; set; }
    }
}
