//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acts29_church_line_page_website_group
    {
        public long aid { get; set; }
        public Nullable<long> acts29_church_aid { get; set; }
        public int page_website_group_aid { get; set; }
        public Nullable<byte> disable { get; set; }
        public Nullable<byte> if_default { get; set; }
    }
}
