//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class acts29_church
    {
        public long aid { get; set; }
        public string acts29_church_id { get; set; }
        public string acts29_church_name { get; set; }
        public string acts29_church_contact_name1 { get; set; }
        public string acts29_church_phone1 { get; set; }
        public string acts29_church_email1 { get; set; }
        public string acts29_church_contact_name2 { get; set; }
        public string acts29_church_phone2 { get; set; }
        public string acts29_church_email2 { get; set; }
        public string acts29_church_address { get; set; }
        public string acts29_church_fax { get; set; }
        public string acts29_church_website { get; set; }
        public string acts29_church_domain_name { get; set; }
        public string acts29_church_domain_ip { get; set; }
        public string acts29_church_url_rewrite_id { get; set; }
        public string acts29_church_law_id { get; set; }
        public Nullable<int> acts29_church_account_aid { get; set; }
        public string acts29_church_valid_start_date { get; set; }
        public string acts29_church_valid_end_date { get; set; }
        public string acts29_church_note { get; set; }
        public Nullable<byte> if_active { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
        public Nullable<byte> disable { get; set; }
    }
}
