//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class cos_faculty_info_tu
    {
        public long aid { get; set; }
        public string faculty_name { get; set; }
        public string faculty_name_en { get; set; }
        public string faculty_desc { get; set; }
        public Nullable<long> dean_aid { get; set; }
        public Nullable<long> dean_assistant_aid { get; set; }
        public Nullable<long> home_images_aid { get; set; }
        public Nullable<long> cosmap_images_aid { get; set; }
        public string css_style_name { get; set; }
        public Nullable<int> style_sequence { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
        public Nullable<long> acts29_church_aid { get; set; }
    }
}
