//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_line_booking_datetime
    {
        public long aid { get; set; }
        public Nullable<long> booking_aid { get; set; }
        public Nullable<int> location_aid { get; set; }
        public string booking_date { get; set; }
        public string booking_start_time { get; set; }
        public string booking_end_time { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
    }
}
