//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_line_organization_booking
    {
        public int aid { get; set; }
        public Nullable<int> prm_organization_privilege_aid { get; set; }
        public Nullable<int> location_aid_1 { get; set; }
        public Nullable<int> location_aid_2 { get; set; }
        public Nullable<int> location_aid_3 { get; set; }
        public Nullable<byte> week_type { get; set; }
        public string booking_start_time { get; set; }
        public string booking_end_time { get; set; }
        public Nullable<long> account_id { get; set; }
        public Nullable<int> score { get; set; }
        public Nullable<byte> disable { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
    }
}
