//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class location_info
    {
        public int aid { get; set; }
        public string name { get; set; }
        public string place_type_d_option_aid { get; set; }
        public string place_type_other_d_option_text { get; set; }
        public Nullable<int> place_size { get; set; }
        public Nullable<int> use_range_max { get; set; }
        public Nullable<int> use_range_min { get; set; }
        public string description { get; set; }
        public string equipment_d_option_aid { get; set; }
        public string equipment_other_d_option_text { get; set; }
        public Nullable<byte> if_allow_eatting { get; set; }
        public Nullable<byte> if_allow_booking { get; set; }
        public Nullable<byte> if_allow_group { get; set; }
        public Nullable<byte> if_approve { get; set; }
        public Nullable<byte> disable { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
        public Nullable<long> acts29_church_aid { get; set; }
    }
}
