//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_line_images
    {
        public long aid { get; set; }
        public Nullable<long> member_aid { get; set; }
        public string member_image_description { get; set; }
        public string original_file_name { get; set; }
        public string system_file_name { get; set; }
        public Nullable<int> image_type { get; set; }
        public Nullable<byte> disable { get; set; }
    }
}
