//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member
    {
        public long aid { get; set; }
        public string member_name_mandarin { get; set; }
        public string member_name_english { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string member_taiwan_id { get; set; }
        public string member_passport_id { get; set; }
        public string gender { get; set; }
        public string birthday { get; set; }
        public string blood_type { get; set; }
        public string address { get; set; }
        public string telephoneH { get; set; }
        public string telephoneO { get; set; }
        public string cell_phone { get; set; }
        public Nullable<byte> disable { get; set; }
        public string build_datetime { get; set; }
        public Nullable<int> login_total_times { get; set; }
        public string backend_comments { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
    }
}
