//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_line_prm_organiztion_audit
    {
        public long aid { get; set; }
        public long member_aid { get; set; }
        public string audit_checklist { get; set; }
        public Nullable<int> flow_origination { get; set; }
        public Nullable<int> flow_destination { get; set; }
        public Nullable<int> status { get; set; }
        public string backend_comments { get; set; }
        public string build_datetime { get; set; }
    }
}
