//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_line_prm_info
    {
        public long aid { get; set; }
        public long member_aid { get; set; }
        public Nullable<int> prm_organization_privilege_aid { get; set; }
        public Nullable<long> account_aid { get; set; }
        public Nullable<int> faith_type { get; set; }
        public Nullable<int> sunday_type { get; set; }
        public Nullable<byte> if_follow { get; set; }
        public Nullable<byte> if_missing { get; set; }
        public Nullable<byte> if_baptized { get; set; }
        public string baptized_date { get; set; }
        public Nullable<int> marriage_type { get; set; }
        public string mate_name { get; set; }
        public string career { get; set; }
        public string graduation_school { get; set; }
        public string survey_comment { get; set; }
        public string missing_d_option_aid { get; set; }
        public string missing_organization_text { get; set; }
        public string missing_note { get; set; }
        public Nullable<long> link_account_aid { get; set; }
    }
}
