//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_line_cos_lesson_info
    {
        public long member_aid { get; set; }
        public long cos_lession_aid { get; set; }
        public string check_stauts { get; set; }
        public Nullable<byte> if_pass { get; set; }
        public string backend_comments { get; set; }
    }
}
