//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public long aid { get; set; }
        public string news_subject { get; set; }
        public string news_content { get; set; }
        public string news_link { get; set; }
        public Nullable<byte> link_type { get; set; }
        public Nullable<int> img_type { get; set; }
        public Nullable<byte> if_top { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string publish_start_date { get; set; }
        public string publish_start_time { get; set; }
        public string publish_end_date { get; set; }
        public string publish_end_time { get; set; }
        public string page_website_group_aid_string { get; set; }
        public Nullable<byte> disable { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
        public Nullable<int> acts29_church_aid { get; set; }
    }
}
