//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class page
    {
        public int pageid { get; set; }
        public Nullable<int> parentid { get; set; }
        public Nullable<int> groupid { get; set; }
        public string name { get; set; }
        public string link { get; set; }
        public string target { get; set; }
        public Nullable<byte> readable { get; set; }
        public Nullable<short> sequence { get; set; }
        public string page_website_group_name { get; set; }
        public Nullable<int> page_website_group_aid { get; set; }
        public Nullable<byte> if_need_set_privilege_read { get; set; }
        public Nullable<byte> if_need_set_privilege_update { get; set; }
        public Nullable<byte> if_need_set_privilege_add { get; set; }
        public Nullable<byte> if_need_set_privilege_delete { get; set; }
    }
}
