//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class page_website_group
    {
        public int aid { get; set; }
        public string website_group_name { get; set; }
        public string website_group_display_name { get; set; }
        public string website_group_description { get; set; }
        public Nullable<byte> if_general_group { get; set; }
        public Nullable<byte> if_open_online { get; set; }
        public string base_url_testing1 { get; set; }
        public string base_url_testing2 { get; set; }
        public string base_url_on_line { get; set; }
    }
}
