//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class prm_temp_recursive_privlilege
    {
        public int aid { get; set; }
        public int rec_org_aid { get; set; }
        public Nullable<int> parentid { get; set; }
        public string organization_name { get; set; }
        public Nullable<int> lvl { get; set; }
        public long acts29_church_aid { get; set; }
        public byte disable { get; set; }
        public long account_aid { get; set; }
    }
}
