//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class schedule_recurrence
    {
        public long aid { get; set; }
        public string start_date { get; set; }
        public string event_start_time { get; set; }
        public string event_end_time { get; set; }
        public string frequencytype { get; set; }
        public Nullable<int> typetimes { get; set; }
        public Nullable<int> frequencytimes { get; set; }
        public string end_date { get; set; }
        public Nullable<byte> disable { get; set; }
    }
}
