//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class temp_member_line_prm_info
    {
        public long aid { get; set; }
        public long member_aid { get; set; }
        public Nullable<int> prm_organization_privilege_aid { get; set; }
        public Nullable<long> account_aid { get; set; }
        public Nullable<int> faith_type { get; set; }
        public Nullable<int> sunday_type { get; set; }
        public Nullable<byte> if_follow { get; set; }
        public Nullable<byte> if_missing { get; set; }
        public string first_visit_time { get; set; }
        public Nullable<int> first_visit_type { get; set; }
        public Nullable<int> ageold_type { get; set; }
        public Nullable<int> marriage_type { get; set; }
        public string mate_name { get; set; }
        public string career { get; set; }
        public string graduation_school { get; set; }
        public string invited_byfriend_name { get; set; }
        public string invited_byfriend_phone { get; set; }
        public string invited_byfamily_name { get; set; }
        public string invited_byfamily_phone { get; set; }
        public string survey_know_torch_d_option_aid { get; set; }
        public string survey_know_torch_other_d_option_text { get; set; }
        public string survey_like_torch_d_option_aid { get; set; }
        public string survey_like_torch_other_d_option_text { get; set; }
        public string survey_improve_torch_d_option_aid { get; set; }
        public string survey_improve_torch_other_d_option_text { get; set; }
        public string survey_srv_torch_d_option_aid { get; set; }
        public string survey_srv_torch_other_d_option_text { get; set; }
        public string survey_comment { get; set; }
        public string missing_note { get; set; }
    }
}
