//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Acts29Torch.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class tra_cashflow_atm_line_refund_info
    {
        public long aid { get; set; }
        public Nullable<long> tra_cashflow_atm_aid { get; set; }
        public string tra_account_name { get; set; }
        public Nullable<long> tra_account_id { get; set; }
        public string tra_bank_name { get; set; }
        public string tra_bank_branches { get; set; }
        public Nullable<decimal> tra_refund_money { get; set; }
        public Nullable<byte> disable { get; set; }
        public string comments { get; set; }
        public string build_datetime { get; set; }
        public string last_mod_time { get; set; }
        public Nullable<int> last_mod_user_aid { get; set; }
    }
}
